### ISSUE TITLE
Is this paper extended from the conference paper in ICRA 2021?

### ISSUE THREAD

**Issue by zhh2005757** [rpng/MINS#15]
Nice work !!. Is this paper extended from paper Efficient Multi-sensor Aided Inertial Navigation with Online Calibration ?

**Comment by WoosikLee2510** [comment]
Hi @zhh2005757. Yes, the paper is extended from "Efficient Multi-sensor Aided Inertial Navigation with Online Calibration" adding many features and functionalities.

**Comment by zhh2005757** [comment]
Thanks for your reply !!

**Comment by zhh2005757** [comment]
Thanks for your reply !!
