### ISSUE TITLE
Formular does not make sense

### ISSUE THREAD

**Issue by qpc001** [rpng/MINS#16]
in 

```
bool I_Initializer::initialization(Matrix<double, 17, 1> &imustate) {

...

  Vector3d z_axis = a_avg_2to1 / a_avg_2to1.norm();

  // Create an x_axis
  Vector3d e_1(1, 0, 0);

  // Make x_axis perpendicular to z
  Vector3d x_axis = e_1 - z_axis * z_axis.transpose() * e_1;
  x_axis = x_axis / x_axis.norm();

...
```

Why x_axis perpendicular z_axis?  x_axis.dot(z_axis) is not equal to zero.

**Comment by WoosikLee2510** [comment]
This process is called [Gram–Schmidt process](https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process).

If you multiply z_axis.transpose() to x_axis, you will see it become 0.
