### ISSUE TITLE
IMU Coordinate and Camera coordinate 

### ISSUE THREAD

**Issue by zvxvd** [rpng/MINS#19]
i want use my own dataset to test MINS system,  after check the openvins project ,  i am really confused about the IMU coordinate and Camera coordinate , could you please just tell me what imu coordiante this system use:

what i understand:

camera:
[
Z: forward
X: left
Y: down
]

IMU [
X：?
Y: ?
Z: ?
]
what i need ito do is calculate the camera - imu rotation matrix. 

now i don't know how to define imu coordinate .

**Comment by WoosikLee2510** [comment]
So if you are not clear about IMU corridiante, I recommand following [Kalibr](https://github.com/ethz-asl/kalibr) which shares the same coordinate definition of sensor coordinate. Try running Kalibr and using it should work.
