### ISSUE TITLE
Tw, Tg, Ta,  R_IMUtoGYRO，Fail to appear

### ISSUE THREAD

**Issue by wuchong112** [rpng/MINS#24]
There is a transformation matrix T for the angular velocity and acceleration in the imu parameters, in openvins. But in mins this parameter is not in the yaml file, don't you need to worry about that?

**Comment by WoosikLee2510** [comment]
MINS does not support the IMU intrinsic calibration. As long as the IMU has reasonable performance, it should work with MINS.
