### ISSUE TITLE
慢慢的一直朝着一个方向飘走了。。。。

### ISSUE THREAD

**Issue by yst-one** [rpng/MINS#26]
![image](https://github.com/rpng/MINS/assets/134467913/53553cff-bdbe-41e5-829c-ca44ca595dd4)

**Comment by WoosikLee2510** [comment]
I think you have some initialization issues, right?
What was the [imu_thresh](https://github.com/rpng/MINS/blob/master/mins/config/euroc_mav/config_init.yaml#L5C3-L5C13) you used to detect "jerk" and how much were the IMU readings?

**Comment by WoosikLee2510** [comment]
Closed as no response.
