### ISSUE TITLE
Data set connection lost

### ISSUE THREAD

**Issue by woshigagaga** [rpng/MINS#27]

**Comment by FengyuGuo** [comment]
KAIST Urban dataset can not download now.

**Comment by lingtong-seu** [comment]
hope to fix the link

**Comment by WoosikLee2510** [comment]
I updated the links, please check if it works for you.
It was because Google started to charge universities for their google drive usage and I had to move our data.

**Comment by FengyuGuo** [comment]
It works! Thanks!

**Comment by weihaoysgs** [comment]
the link is closed now?
