### ISSUE TITLE
Can you share the  Trail dataset?

### ISSUE THREAD

**Issue by tunan1111** [rpng/MINS#29]
Thank you for your great work. 
We have carefully read your paper.
We want to conduct research on your Trail  dataset，Can you share it？
<img width="296" alt="企业微信截图_1715831120333" src="https://github.com/rpng/MINS/assets/51819217/e89df098-3648-4763-b50c-7bcd186a9235">

**Comment by WoosikLee2510** [comment]
Sorry. Currently, we do not have a plan to open-source the dataset.

**Comment by tunan1111** [comment]
Unfortunately, you are unable to open source the dataset. I believe that your dataset and paper have research value. Finally, thank you for your reply.
