### ISSUE TITLE
Cannot able get rviz config

### ISSUE THREAD

**Issue by Narla-Venkata-Anand-Sai-Kumar** [rpng/MINS#35]
![Screenshot from 2024-07-22 23-48-08](https://github.com/user-attachments/assets/225a4e87-f1a7-48de-a59f-7d2e75b289d2)

I couldnt see the mapping visualization

**Comment by WoosikLee2510** [comment]
Hi @Narla-Venkata-Anand-Sai-Kumar . Could you try `File -> Open Config -> (Select rviz file) $MINS/catkin_ws/src/MINS/mins/launch/display.rviz` ?
