### ISSUE TITLE
Livox Mid-360

### ISSUE THREAD

**Issue by muttistefano** [rpng/MINS#41]
Hi all, and thanks for the great work.
Is there a way to make the MID360 and its 6-axis IMU work with MINS?
I am experiencing a lot of drift; when I turn the lidar, the odometry moves as if I were accelerating in the direction I rotated the sensor.
Is this just because of the parameter tuning and calibration?
Is the lidar rectification method suitable for MID360?
Thanks

**Comment by WoosikLee2510** [comment]
Could you please provide your config and rosbag file so I can look?

**Comment by supersupercoconut** [comment]
> Could you please provide your config and rosbag file so I can look?

Thanks for your work, could you please tell me the imu used in this work is 6 axis or 9-axis

**Comment by WoosikLee2510** [comment]
> > Could you please provide your config and rosbag file so I can look?
> 
> Thanks for your work, could you please tell me the imu used in this work is 6 axis or 9-axis

https://github.com/rpng/MINS/issues/45#issuecomment-2443323115

**Comment by jeannotes** [comment]
hi, for example thiese bags:
https://connecthkuhk-my.sharepoint.com/personal/zhengcr_connect_hku_hk/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fzhengcr%5Fconnect%5Fhku%5Fhk%2FDocuments%2Ffast%2Dlivo2%2Ddataset&ga=1
