### ISSUE TITLE
Does anyone know how to reproduce MINS

### ISSUE THREAD

**Issue by aidadgy** [rpng/MINS#43]
Does anyone know how to reproduce MINS

**Comment by WoosikLee2510** [comment]
Hi, @aidadgy you should be able to reproduce MINS KAIST benchmark results in the paper by running `roslaunch mins rosbag.launch` with config files under [kaist](https://github.com/rpng/MINS/tree/master/mins/config/kaist) and running comparison algorithm, e.g., `roslaunch mins_eval comparison.launch align_mode:=se3 path_alg:="$BASEDIR/algorithms/" path_gts:="$BASEDIR/truths/" viz_type:="8" > "$BASEDIR/output_se3.txt"`
