### ISSUE TITLE
[KAIST] Process died when use_imu_res is disabled. 

### ISSUE THREAD

**Issue by SchwartzSkipper** [rpng/MINS#5]
Hi, Woosik. Really appreciate this great work!

I am currently running KAIST urban 30 dataset. Everything works fine when using subscribe.launch with the defaut kaist/kaist_LC config.

However, when I try to run with polynomial estimated residuals,  
`mins/config/kaist/kaist_LC/config_estimator.yaml`-> `use_imu_res: false`,
the `[mins_subscribe-2]` process died on startup. 
![Screenshot from 2023-10-11 16-43-17](https://github.com/rpng/MINS/assets/24644523/0a553e32-6f45-4657-ac57-b2f4d694f195)

Could you take a look at this problem? Much appreciated.

**Comment by WoosikLee2510** [comment]
Hi, thanks for using MINS!
I fixed the issue with [commit](00ea4229bfe7ebaa373f090acd935342506ea923).
Try pulling the latest version and let me know if it fixes your problem.

**Comment by SchwartzSkipper** [comment]
Thanks! 
This problem is solved.  😃👍
